# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 3c510ff62c8a31b1f012cd76eb4985dbd52f4833011836f8f8c8c7956e9c1da0975c41bcf52582b34c8994d972e6cf3add6794161ce45750898fdd04f7f526e1

test:
  secret_key_base: 1f1627280825fd87fe507b8f57f8d415b38f03967cdf3a3b7980c51c6448a2e12d14c33d99ef81f763c2fb039f371f4fecac679ec105b720c482bfa2c82640c6

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
